
services:
  flask_app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app  # Mounts the local project directory inside the container
    restart: always
